### ISSUE TITLE
Neues Motor Controller Board

### ISSUE THREAD

**Issue by stesto** [gruener-campus-malchow/10-4-a-robot#16]
Neues Motor Controller Board:

Ryanteck Motor Controller Board
(RTK-000-001)

Wiki: [Wiki Ryanteck/RTK-000-001](https://wiki.ryanteck.uk/Category:RTK-000-001)

Sample: [GitHub Ryanteck/RTK-000-001](https://github.com/ryanteck/RTK-000-001)

**Comment by ijontychie** [comment]
Abgebrochen, da mit dem Controller nur ein oder ausgeschaltet werden kann.

Siehe Pull-Request von heute
